#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

git diff --cached --name-only --diff-filter=ACM | grep '\.vue\|\.js' | xargs npm run format
git diff --cached --name-only --diff-filter=ACM | grep '\.vue\|\.js' | xargs npm run lint:fix

git diff --cached --exit-code --quiet || git add .