#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep -v '^src/\.vue\|\.js')

# フォーマットと lint を実行
npm run format
format_exit_code=$?
npm run lint:fix
lint_exit_code=$?

git add $changed_files

updated_files=$(git diff --cached --name-only --diff-filter=ACM | grep -v '^src/\.vue\|\.js')

if [ -z "$updated_files" ]; then
  echo "No changes were found."
fi

# エラーメッセージを表示
if [ $format_exit_code -ne 0 ]; then
  echo "Error: Format check failed."
fi

if [ $lint_exit_code -ne 0 ]; then
  echo "Error: Lint check failed."
fi

# フォーマットや lint でエラーがあれば終了コード1を返す
[ $format_exit_code -eq 0 ] && [ $lint_exit_code -eq 0 ] || exit 1
